### PR TITLE
Resolved Issue #13

### PR DESCRIPTION
**Pull request by wugology**
Add wugbot header to index.html

### CODE REVIEW

**Comment by dwhieb** [comment]
W00t!

2 things I see doing a quick code review:
* You can take out the white space around the text inside the `<h1>`. We'll control that using the `padding` property in CSS.
* Instead of using `<center>`, try using CSS styling. I think adding this rule to the stylesheet should do the trick:
```
h1 {
  text-align: center; }
```
Now here's something I haven't done before: Do you make the changes, and then make another pull request?

**Comment by wugology** [comment]
I want to do
    h1 {
      text-align: center; }
in the index.html file, NOT the style.css file, right?

> You can take out the white space around the text inside the <h1>. We'll control that using the padding property in CSS.

There's whitespace around the text inside <h1>? o.O

**Comment by dwhieb** [comment]
Nope, the style.css file is correct! In fact, there might already even been an `h1` statement in there, so all you'd need to do is add the `text-align: center;` statement to that.

You *could* add that style rule to index.html, you're right, but for this project we're putting all our css stuff in a separate external stylesheet (style.css). Then near the top of index.html, you'll notice there's a line that says `<link rel='stylesheet'... etc.`. That's the line that tells index.html where to look for its styling.

**Comment by dwhieb** [comment]
I just checked: there is not an `h1` rule in the stylesheet yet. So after the lines that say, 
```
input[type="radio"] {
	align-self: center; }
```
you can add,
```
h1 {
  text-align: center; }
```
(We're putting it there to keep things alphabetical.)

**Comment by dwhieb** [comment]
Oh except apparently I don't know my alphabet. So it should actually come just before this:
```
input {
  background-color: lightgray; }
```

**Comment by wugology** [comment]
I deleted my comment because I thought I had answered my own question, so now you look like you're just talking to yourself. Sorry.

So the thing is, are we sure we want `<h1>` to be centered always site-wide? The homepage is usually a bit different from other pages anyway, so that's why I didn't change it in the style.css file.

**Comment by dwhieb** [comment]
As for the white space thing:
Here's what you've currently got:
```
<h1> digital linguistics for everyone </h1>
```
Instead of this:
```
<h1>digital linguistics for everyone</h1>
```
Those extra white spaces around the text can cause us problems later. You're telling the browser that that white space is *part of* the text. Really what we want is some visual styling to put a little more space around the text (which I assume is what you were trying to do). Instead of using white space to do that, there's a css rule called 'padding' you can use.

**Comment by wugology** [comment]
I deleted those whitespaces. It won't let me make another pull request but there's another commit here: https://github.com/wugology/core/commit/103883e6e664ab8a4b6764edb662864ddf3c7e24

**Comment by dwhieb** [comment]
You're absolutely right about the styling across pages thing. We can handle that in two ways (or more, but these two make the most sense for us):
1. Create one stylesheet, style.css, which contains only the style rules that work for every page on the site. Then create separate stylesheets for each individual page (e.g. index.style, aboutWugbot.style, etc.). Any styles in the page-specific ones will override the site-general ones.
2. Still have the single style.css, but instead of making a bunch of separate style sheets for each page, we just put the styles into the `<head>` of each page. Again, they'll override the more general styles whenever there's a conflict.
3. Just use 1 stylesheet for everything, but use classes to make the distinctions we need. So maybe half our headers are centered and the other half aren't. We can make a class called .centeredHeader and another class called .leftHeader, and just manage it all in the same stylesheet.

We'll probably have some combination of these. I'm not sure. @amundo will have a better idea of this. I think for now, it's best to keep everything in one stylesheet until we can make a decision on this.

**Comment by wugology** [comment]
Okay fixed :) 

https://github.com/wugology/core/commit/3372c7c89f05d919552bd884ef2f10ab0a07f801

**Comment by wugology** [comment]
So what I think just happened is all my updated commits just updated the original pull request. The thing you merged appears to be my latest commit.

**Comment by dwhieb** [comment]
Awesome!

**Comment by dwhieb** [comment]
I made just a few small changes after I merged. The most important one is that I moved the `<h1>` and `` tags from the `<head>` to the `<body>`. The `<head>` is pretty much just for metadata and stuff the user never sees; the `<body>` is the actual content of the page.

**Pull request merged**
